{% set name = "coscine" %}
{% set version = "0.8.1" %}
{% set sha256 = "e859eaac477f09e1632440bb526377ffe50a1073c23ade74edeb79f46c5d19a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - requests-toolbelt
    - tqdm
    - colorama
    - prettytable
    - appdirs
    - rdflib

test:
  imports:
    - coscine
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://git.rwth-aachen.de/coscine/docs/public/coscine-python-sdk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python3 SDK for [Coscine](https://coscine.rwth-aachen.de/)
  description: |
    Coscine Python SDK

    This python3.x package provides an SDK for interfacing with Coscine.
    It is maintained and developed by the community and should not be regarded
    as an official service of RWTH Aachen.
    You can use the package to integrate Coscine in your python applications
    and easily:
    - create, edit or delete projects and resources
    - invite and manage project members
    - upload and download files, resources and projects
    - manage your metadata
  doc_url: https://git.rwth-aachen.de/coscine/docs/public/coscine-python-sdk/-/tree/master/src/examples
  dev_url: https://git.rwth-aachen.de/coscine/docs/public/coscine-python-sdk

extra:
  recipe-maintainers:
    - niklassiemer
