{% set name = "coscine" %}
{% set version = "0.10.3" %}
{% set sha256 = "3229944d82617d97b4c35ca91802e45d6b1c78997807fe3f36d64c3bc2001e96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - boto3
    - pyshacl
    - python-dateutil
    - rdflib
    - requests
    - requests-cache
    - requests-toolbelt
    - tabulate
    - tqdm

test:
  imports:
    - coscine
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://git.rwth-aachen.de/coscine/community-features/coscine-python-sdk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Software Development Kit for Coscine.
  description: |
    The Coscine Python SDK provides a high-level interface
    to the Coscine REST API.
  doc_url: https://coscine.pages.rwth-aachen.de/community-features/coscine-python-sdk
  dev_url: https://git.rwth-aachen.de/coscine/community-features/coscine-python-sdk

extra:
  recipe-maintainers:
    - palomena
    - niklassiemer
